db.Territory.save({"firstName":"Stephen","lastName":"Jiang","territoryID":"0","salesYTD":559697.56,"TerritoryName":"N/A"})
db.Territory.save({"firstName":"Michael","lastName":"Blythe","territoryID":"2","salesYTD":3763178.18,"TerritoryName":"Northeast"})
db.Territory.save({"firstName":"Linda","lastName":"Mitchell","territoryID":"4","salesYTD":4251368.55,"TerritoryName":"Southwest"})
db.Territory.save({"firstName":"Jillian","lastName":"Carson","territoryID":"3","salesYTD":3189418.37,"TerritoryName":"Central"})
db.Territory.save({"firstName":"Garrett","lastName":"Vargas","territoryID":"6","salesYTD":1453719.47,"TerritoryName":"Canada"})
db.Territory.save({"firstName":"Tsvi","lastName":"Reiter","territoryID":"5","salesYTD":2315185.61,"TerritoryName":"Southeast"})
db.Territory.save({"firstName":"Pamela","lastName":"Ansman-Wolfe","territoryID":"1","salesYTD":1352577.13,"TerritoryName":"Northwest"})
db.Territory.save({"firstName":"Shu","lastName":"Ito","territoryID":"4","salesYTD":2458535.62,"TerritoryName":"Southwest"})
db.Territory.save({"firstName":"José","lastName":"Saraiva","territoryID":"6","salesYTD":2604540.72,"TerritoryName":"Canada"})
db.Territory.save({"firstName":"David","lastName":"Campbell","territoryID":"1","salesYTD":1573012.94,"TerritoryName":"Northwest"})
db.Territory.save({"firstName":"Tete","lastName":"Mensa-Annan","territoryID":"1","salesYTD":1576562.20,"TerritoryName":"Northwest"})
db.Territory.save({"firstName":"Syed","lastName":"Abbas","territoryID":"0","salesYTD":172524.45,"TerritoryName":"N/A"})
db.Territory.save({"firstName":"Lynn","lastName":"Tsoflias","territoryID":"9","salesYTD":1421810.92,"TerritoryName":"Australia"})
db.Territory.save({"firstName":"Amy","lastName":"Alberts","territoryID":"0","salesYTD":519905.93,"TerritoryName":"N/A"})
db.Territory.save({"firstName":"Rachel","lastName":"Valdez","territoryID":"8","salesYTD":1827066.71,"TerritoryName":"Germany"})
db.Territory.save({"firstName":"Jae","lastName":"Pak","territoryID":"10","salesYTD":4116871.23,"TerritoryName":"United Kingdom"})
db.Territory.save({"firstName":"Ranjit","lastName":"Varkey Chudukatil","territoryID":"7","salesYTD":3121616.32,"TerritoryName":"France"})